version: '3'
services:
  fivem:
   image: spritsail/fivem
   container_name: fivem
   restart: always
   stdin_open: true
   tty: true
   volumes:
     - /mnt/c/Users/jamie/Projects/NewLife/FiveM:/config
     - /mnt/c/Users/jamie/Projects/NewLife/txData:/txData
   ports:
     - 30120:30120
     - 30120:30120/udp
     - 40120:40120
   environment:
     NO_DEFAULT_CONFIG: 1
     LICENSE_KEY: $CFX_API_KEY
   depends_on:
     - mariadb

  mariadb:
   image: mariadb
   volumes:
     - "/mnt/c/Users/jamie/Projects/NewLife/mysql_data:/var/lib/mysql"
   environment:
     MYSQL_DATABASE: $DB_NAME
     MYSQL_USER: $DB_USER
     MYSQL_PASSWORD: $DB_PASS
     MYSQL_RANDOM_ROOT_PASSWORD: 0
     TZ: Europe/Brussels

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8100-8105:80
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
